<a href="https://colab.research.google.com/github/Ayushi-creator/Datascience-ML-and-AI/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5])
print(type(arr))

<class 'numpy.ndarray'>


In [3]:
print(arr.ndim)

1


In [4]:
arr.dtype

dtype('int64')

In [5]:
arr = np.array([1,2,3,4,5],dtype="uint8")
arr.dtype

dtype('uint8')

In [6]:
arr = np.array([1,2,3,4,5,6.6])
arr.dtype

dtype('float64')

##Time

In [9]:
lst = [1]*1000

In [10]:
print(lst)
print(len(lst))
print(type(lst))

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 

In [11]:
arr = np.ones(10000,dtype="uint8")

In [12]:
print(arr)

[1 1 1 ... 1 1 1]


In [13]:
%timeit sum(lst)

8.15 µs ± 198 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [14]:
%timeit arr.sum()

14.3 µs ± 2.28 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [15]:
%timeit sum(arr)

1.52 ms ± 15.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


Numpy stands for numerical Python.

It is a library of python to work with Arrays

In [17]:
arr = np.ones(5)

In [18]:
arr

array([1., 1., 1., 1., 1.])

In [19]:
arr.dtype

dtype('float64')

In [20]:
arr = np.ones((3,4),dtype="uint8")

In [21]:
print(arr)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [22]:
arr = np.zeros((3,4),dtype="int8")

In [23]:
arr

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int8)

In [24]:
arr.shape

(3, 4)

In [25]:
arr = np.arange(2,10,2)
print(arr)

[2 4 6 8]


In [26]:
arr.shape

(4,)

##Sclicing

numpy slicing is shallow copy python does deep copy

In [27]:
arr = np.arange(5,25,2)
print(arr)

[ 5  7  9 11 13 15 17 19 21 23]


In [28]:
arr[2:5]

array([ 9, 11, 13])

In [29]:
lst = [1,2,3,4,5]
lst2 = lst[2:4]
print(lst)
print(lst2)
lst2[0] = 1000
print(lst)
print(lst2)

[1, 2, 3, 4, 5]
[3, 4]
[1, 2, 3, 4, 5]
[1000, 4]


In [30]:
arr = np.array([1,2,3,4,5])
arr2 = arr[2:4]
print(arr)
print(arr2)
arr2[0] = 1000
print(arr)
print(arr2)

[1 2 3 4 5]
[3 4]
[   1    2 1000    4    5]
[1000    4]


In [31]:
arr = np.array([1,2,3,4,5])
arr2 = arr[2:4].copy()
print(arr)
print(arr2)
arr2[0] = 1000
print(arr)
print(arr2)

[1 2 3 4 5]
[3 4]
[1 2 3 4 5]
[1000    4]
